declare type MatchType = {
  champion: number,
  gameId: number,
  lane: string,
  platformId: string,
  queue: number,
  role: string,
  season: number,
  timestamp: number,
}

declare type MatchDetailType = {
  gameCreation: number,
  gameDuration: number,
  gameId: number,
  gameMode: string,
  gameType: string,
  gameVersion: string,
  mapId: number,
  participants: Array<ParticipantsType>,
  participantIdentities: Array<ParticipantIdentitiesType>,
  platformId: string,
  queueId: number,
  seasonId: number,
  teams: Array<TeamType>,
}

declare type TeamType = {
  bans: Array<{
    championId: number,
    pickTurn: number,
  }>,
  baronKills: number,
  dominionVictoryScore: number,
  dragonKills: number,
  firstBaron: boolean,
  firstBlood: boolean,
  firstDragon: boolean,
  firstInhibitor: boolean,
  firstRiftHerald: boolean,
  firstTower: boolean,
  inhibitorKills: number,
  riftHeraldKills: number,
  teamId: number,
  towerKills: number,
  vilemawKills: number,
  win: string,
}

declare type PlayerType = {
  accountId: string,
  currentAccountId: string,
  currentPlatformId: string,
  matchHistoryUri: string,
  platformId: string,
  profileIcon: number,
  summonerId: string,
  summonerName: string,
}

declare type ParticipantIdentitiesType = {
  participantId: number,
  player: PlayerType,
}

declare type ParticipantsType = {
  championId: number,
  highestAchievedSeasonTier: string,
  participantId: number,
  spell1Id: number,
  spell2Id: number,
  stats: {
    assists: number,
    champLevel: number,
    combatPlayerScore: number,
    damageDealtToObjectives: number,
    damageDealtToTurrets: number,
    damageSelfMitigated: number,
    deaths: number,
    doubleKills: number,
    firstBloodAssist: boolean,
    firstBloodKill: boolean,
    firstInhibitorAssist: boolean,
    firstInhibitorKill: boolean,
    firstTowerAssist: boolean,
    firstTowerKill: boolean,
    goldEarned: number,
    goldSpent: number,
    inhibitorKills: number,
    item0: number,
    item1: number,
    item2: number,
    item3: number,
    item4: number,
    item5: number,
    item6: number,
    killingSprees: number,
    kills: number,
    largestCriticalStrike: number,
    largestKillingSpree: number,
    largestMultiKill: number,
    longestTimeSpentLiving: number,
    magicalDamageTaken: number,
    magicDamageDealt: number,
    magicDamageDealtToChampions: number,
    neutralMinionsKilled: number,
    neutralMinionsKilledEnemyJungle: number,
    neutralMinionsKilledTeamJungle: number,
    objectivePlayerScore: number,
    participantId: number,
    pentaKills: number,
    perk0: number,
    perk0Var1: number,
    perk0Var2: number,
    perk0Var3: number,
    perk1: number,
    perk1Var1: number,
    perk1Var2: number,
    perk1Var3: number,
    perk2: number,
    perk2Var1: number,
    perk2Var2: number,
    perk2Var3: number,
    perk3: number,
    perk3Var1: number,
    perk3Var2: number,
    perk3Var3: number,
    perk4: number,
    perk4Var1: number,
    perk4Var2: number,
    perk4Var3: number,
    perk5: number,
    perk5Var1: number,
    perk5Var2: number,
    perk5Var3: number,
    perkPrimaryStyle: number,
    perkSubStyle: number,
    physicalDamageDealt: number,
    physicalDamageDealtToChampions: number,
    physicalDamageTaken: number,
    playerScore0: number,
    playerScore1: number,
    playerScore2: number,
    playerScore3: number,
    playerScore4: number,
    playerScore5: number,
    playerScore6: number,
    playerScore7: number,
    playerScore8: number,
    playerScore9: number,
    quadraKills: number,
    sightWardsBoughtInGame: number,
    statPerk0: number,
    statPerk1: number,
    statPerk2: number,
    timeCCingOthers: number,
    totalDamageDealt: number,
    totalDamageDealtToChampions: number,
    totalDamageTaken: number,
    totalHeal: number,
    totalMinionsKilled: number,
    totalPlayerScore: number,
    totalScoreRank: number,
    totalTimeCrowdControlDealt: number,
    totalUnitsHealed: number,
    tripleKills: number,
    trueDamageDealt: number,
    trueDamageDealtToChampions: number,
    trueDamageTaken: number,
    turretKills: number,
    unrealKills: number,
    visionScore: number,
    visionWardsBoughtInGame: number,
    wardsKilled: number,
    wardsPlaced: number,
    win: boolean,
  },
  teamId: number,
  timeline: {
    creepsPerMinDeltas: {
      '0-10': number,
      '10-20': number,
    },
    damageTakenPerMinDeltas: {
      '0-10': number,
      '10-20': number,
    },
    goldPerMinDeltas: {
      '0-10': number,
      '10-20': number,
    },
    lane: string,
    participantId: number,
    role: string,
    xpPerMinDeltas: {
      '0-10': number,
      '10-20': number,
    },
  },
}
