declare type StaticDataType = {
  allchampions: SummonerAllChampionsType,
  summonerspells: SummonerSummonerSpellsType,
  items: SummonerItemsType,
  isFetching: boolean,
  error: ?string,
}

declare type SummonerAllChampionsType = {
  type: string,
  format: string,
  version: string,
  data: {
    [key: string]: {
      version: string,
      id: string,
      key: string,
      name: string,
      title: string,
      blurb: string,
      info: {
        attack: number,
        defense: number,
        magic: number,
        difficulty: number,
      },
      image: {
        full: string,
        sprite: string,
        group: string,
        x: number,
        y: number,
        w: number,
        h: number,
      },
      tags: Array<string>,
      partype: string,
      stats: {
        hp: number,
        hpperlevel: number,
        mp: number,
        mpperlevel: number,
        movespeed: number,
        armor: number,
        armorperlevel: number,
        spellblock: number,
        spellblockperlevel: number,
        attackrange: number,
        hpregen: number,
        hpregenperlevel: number,
        mpregen: number,
        mpregenperlevel: number,
        crit: number,
        critperlevel: number,
        attackdamage: number,
        attackdamageperlevel: number,
        attackspeedperlevel: number,
        attackspeed: number,
      },
    },
  },
}

declare type SummonerDataType = {
  id: string,
  name: string,
  description: string,
  tooltip: string,
  maxrank: number,
  cooldown: Array<number>,
  cooldownBurn: string,
  cost: Array<number>,
  costBurn: string,
  datavalues: {},
  effect: Array<?Array<number>>,
  effectBurn: Array<?string>,
  vars: Array<string>,
  key: string,
  summonerLevel: number,
  modes: Array<string>,
  costType: string,
  maxammo: string,
  range: Array<number>,
  rangeBurn: string,
  image: {
    full: string,
    sprite: string,
    group: string,
    x: number,
    y: number,
    w: number,
    h: number,
  },
  resource: string,
}

declare type SummonerSummonerSpellsType = {
  type: string,
  version: string,
  data: {
    SummonerBarrier: SummonerDataType,
    SummonerBoost: SummonerDataType,
    SummonerDot: SummonerDataType,
    SummonerExhaust: SummonerDataType,
    SummonerFlash: SummonerDataType,
    SummonerHaste: SummonerDataType,
    SummonerHeal: SummonerDataType,
    SummonerMana: SummonerDataType,
    SummonerOdysseyFlash: SummonerDataType,
    SummonerOdysseyRevive: SummonerDataType,
    SummonerPoroRecall: SummonerDataType,
    SummonerPoroThrow: SummonerDataType,
    SummonerSmite: SummonerDataType,
    SummonerSnowURFSnowball_Mark: SummonerDataType,
    SummonerSnowball: SummonerDataType,
    SummonerTeleport: SummonerDataType,
  },
}

declare type SummonerItemsType = {
  type: string,
  version: string,
  basic: {
    name: string,
    rune: {},
    gold: {},
    group: string,
    description: string,
    colloq: string,
    plaintext: string,
    consumed: boolean,
    stacks: number,
    depth: number,
    consumeOnFull: boolean,
    from: Array<string>,
    into: Array<string>,
    specialRecipe: number,
    inStore: boolean,
    hideFromAll: boolean,
    requiredChampion: string,
    requiredAlly: string,
    stats: {
      [key: string]: number,
    },
    tags: Array<string>,
    maps: {
      [key: number]: boolean,
    },
  },
  data: {
    [key: number]: {
      name: string,
      description: string,
      colloq: string,
      plaintext: string,
      into: Array<string>,
      image: {
        full: string,
        sprite: string,
        group: string,
        x: number,
        y: number,
        w: number,
        h: number,
      },
      gold: {
        base: number,
        purchasable: boolean,
        total: number,
        sell: number,
      },
      tags: Array<string>,
      maps: {
        [key: number]: boolean,
      },
      stats: {
        FlatMovementSpeedMod: number,
      },
    },
  },
  groups: {
    [key: number]: {
      id: string,
      MaxGroupOwnable: string,
    },
  },
  tree: Array<{
    header: string,
    tags: Array<string>,
  }>,
}
