declare type SummonerType = {
  accountId: string,
  freshBlood: boolean,
  hotStreak: boolean,
  id: string,
  inactive: boolean,
  leagueId: string,
  leaguePoints: number,
  losses: number,
  name: string,
  profileIconId: number,
  puuid: string,
  queueType: string,
  rank: string,
  revisionDate: number,
  summonerId: string,
  summonerLevel: number,
  summonerName: string,
  tier: string,
  veteran: boolean,
  wins: number,
  error: string,
}
