declare type SummonerType = {
  accountId: string,
  freshBlood: boolean,
  hotStreak: boolean,
  id: string,
  inactive: boolean,
  leagueId: string,
  leaguePoints: number,
  losses: number,
  name: string,
  profileIconId: number,
  puuid: string,
  queueType: string,
  rank: string,
  revisionDate: number,
  summonerId: string,
  summonerLevel: number,
  summonerName: string,
  tier: string,
  veteran: boolean,
  wins: number,
  leagueName: string,
  error: string,
}

declare type MyLeagueType = {
  leagueId: string,
  queueType: string,
  tier: string,
  rank: string,
  summonerId: string,
  summonerName: string,
  leaguePoints: number,
  wins: number,
  losses: number,
  veteran: boolean,
  inactive: boolean,
  freshBlood: boolean,
  hotStreak: boolean,
  isFetching: boolean,
  error: ?string,
}

declare type LeagueType = {
  error: ?string,
  isFetching: boolean,
  leagueId: string,
  name: string,
  queue: string,
  tier: string,
}
